### ISSUE TITLE
Discussion about the code written p 48

### ISSUE THREAD

**Issue by vlaurier** [dddinphp/ddd-in-php-book-issues#8]
Hello,

I'm new to DDD, but I would like to underline a part of the implementation that look doubtful to me.
At page 48, the goal of the value object "OrderId" is to handle the identity for an order, right ? And so, it should encapsulate all the required logic for that identity to be consistent. But you say the creation of the identity would be inside a Repository, and show this example for the implementation:

Inside the OrderId object:

public static function create($anId) {
    return new static($anId);
}

So you allow the developer to instanciate, anywhere, at any time, an OrderId, even not consistent, like this one: $orderId = new OrderId('An invalid id');

In your example, the check is done inside the repository:

public function nextIdentity() {
   return OrderId::create(
      strtoupper(Uuid::uuid4())
   );
}

Why ? I think it is not the responsibility to the repository to ensure the consistency of the OrderId object. Should that part of code be moved from the repository to the OrderId object ?

Excuse me if there are some mistakes in my sentences. English is not my mothertongue. I hope you get the point however.

Regards, 

Vincent.

**Comment by keyvanakbary** [comment]
Sorry for the delay, we've been a little bit busy. So the idea is of the `OrderId` is to encapsulate and represent the _identity_ of an order. How do you represent that identity _technically_ is not a concern of the domain layer.

What this means is that on an _in-memory_ implementation might be just an auto-incremental integer, on a PostgreSQL implementation would be an auto-incremental sequence or on a MongoDB an `ObjectId`. Most of the time a `Uuid` will be good enough for all cases, that's why sometimes this leaves inside the domain as an internal detail of the Value Object itself, for _convenience_. The eternal debate between _convenience_ vs _purity_. I hope that helps :)
